const posts = [
    {
      _id: "1",
      title: "Beautiful Sunset",
      description: "Enjoying the beautiful sunset at the beach.",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "public",
      likes: 15,
      comments: 3,
      author: {
        name: "Alice",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-01",
    },
    {
      _id: "2",
      title: "Mountain Hike",
      description: "Had an amazing hike in the mountains today!",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "friends",
      likes: 20,
      comments: 5,
      author: {
        name: "Bob",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-02",
    },
    {
      _id: "3",
      title: "New Recipe",
      description: "Tried a new recipe today. It turned out great!",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "private",
      likes: 8,
      comments: 2,
      author: {
        name: "Charlie",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-03",
    },
    {
      _id: "4",
      title: "City Lights",
      description: "The city looks amazing at night.",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "public",
      likes: 25,
      comments: 7,
      author: {
        name: "Diana",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-04",
    },
    {
      _id: "5",
      title: "Road Trip",
      description: "Going on a road trip this weekend. Can't wait!",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "friends",
      likes: 12,
      comments: 4,
      author: {
        name: "Eve",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-05",
    },
    {
      _id: "6",
      title: "New Puppy",
      description: "Just got a new puppy. Meet Max!",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "public",
      likes: 30,
      comments: 10,
      author: {
        name: "Frank",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-06",
    },
    {
      _id: "7",
      title: "Art Exhibition",
      description: "Visited an amazing art exhibition today.",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "public",
      likes: 18,
      comments: 6,
      author: {
        name: "Grace",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-07",
    },
    {
      _id: "8",
      title: "Yoga Session",
      description: "Relaxing yoga session this morning.",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "private",
      likes: 10,
      comments: 1,
      author: {
        name: "Hank",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-08",
    },
    {
      _id: "9",
      title: "Book Recommendation",
      description: "Just finished reading an amazing book. Highly recommend it!",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "public",
      likes: 22,
      comments: 8,
      author: {
        name: "Ivy",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-09",
    },
    {
      _id: "10",
      title: "Coffee Break",
      description: "Enjoying a quiet coffee break.",
      mediaType: "image",
      mediaUrl: "https://via.placeholder.com/600x400",
      privacy: "friends",
      likes: 14,
      comments: 3,
      author: {
        name: "Jack",
        avatar: "https://via.placeholder.com/150",
      },
      date: "2023-10-10",
    },
  ];
  
  export default posts;